# Generated by Django 4.1.3 on 2022-12-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_password',
            name='Confirm_new_password',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='change_password',
            name='New_password',
            field=models.IntegerField(blank=True),
        ),
    ]
