# Generated by Django 4.1.3 on 2022-12-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_alter_change_password_confirm_new_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
