# Generated by Django 4.1.3 on 2022-12-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_alter_account_details_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='change_password',
            name='Confirm_new_password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='change_password',
            name='New_password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
