# Generated by Django 4.1.3 on 2022-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0004_alter_account_details_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_password',
            name='Old_password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
